//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denLanguageResourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("denLanguageResourses.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Country.
        /// </summary>
        public static string AddCountry {
            get {
                return ResourceManager.GetString("AddCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Market.
        /// </summary>
        public static string AddMarket {
            get {
                return ResourceManager.GetString("AddMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Marketplace.
        /// </summary>
        public static string AddMarketplace {
            get {
                return ResourceManager.GetString("AddMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new address label template.
        /// </summary>
        public static string AddNewAddressLabelTemplate {
            get {
                return ResourceManager.GetString("AddNewAddressLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new product label template.
        /// </summary>
        public static string AddNewProductLabelTemplate {
            get {
                return ResourceManager.GetString("AddNewProductLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new return label template.
        /// </summary>
        public static string AddNewReturnLabelTemplate {
            get {
                return ResourceManager.GetString("AddNewReturnLabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add supplier.
        /// </summary>
        public static string AddSupplier {
            get {
                return ResourceManager.GetString("AddSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to QuickBooks.
        /// </summary>
        public static string AddToQuickBooks {
            get {
                return ResourceManager.GetString("AddToQuickBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All orders unselected.
        /// </summary>
        public static string AllOrdersUnselected {
            get {
                return ResourceManager.GetString("AllOrdersUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon Orders Bash.
        /// </summary>
        public static string AmazonOrdersBash {
            get {
                return ResourceManager.GetString("AmazonOrdersBash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign MPN.
        /// </summary>
        public static string AssignMPN {
            get {
                return ResourceManager.GetString("AssignMPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign new supplier.
        /// </summary>
        public static string AssignNewSupplier {
            get {
                return ResourceManager.GetString("AssignNewSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back 7 Days.
        /// </summary>
        public static string Back7Days {
            get {
                return ResourceManager.GetString("Back7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booting up.
        /// </summary>
        public static string BootingUp {
            get {
                return ResourceManager.GetString("BootingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Bottom Font&apos; must be greater than 0..
        /// </summary>
        public static string BottomFontMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("BottomFontMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin.
        /// </summary>
        public static string BottomMargin {
            get {
                return ResourceManager.GetString("BottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Bottom Margin&apos; must not be negative..
        /// </summary>
        public static string BottomMarginMustNotBeNegative {
            get {
                return ResourceManager.GetString("BottomMarginMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Address.
        /// </summary>
        public static string BusinessAddressLabel {
            get {
                return ResourceManager.GetString("BusinessAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Details.
        /// </summary>
        public static string BusinessDetails {
            get {
                return ResourceManager.GetString("BusinessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessNameLabel {
            get {
                return ResourceManager.GetString("BusinessNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        public static string BuyerLabel {
            get {
                return ResourceManager.GetString("BuyerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot establish connection with eBay server.
        /// </summary>
        public static string CannotConnectEbay {
            get {
                return ResourceManager.GetString("CannotConnectEbay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Central Line Spacing&apos; must not be negative..
        /// </summary>
        public static string CentralLineSpacingMustNotBeNegative {
            get {
                return ResourceManager.GetString("CentralLineSpacingMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change MPN.
        /// </summary>
        public static string ChangeMPN {
            get {
                return ResourceManager.GetString("ChangeMPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string ChangeStatusButtonText {
            get {
                return ResourceManager.GetString("ChangeStatusButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change terminal theme.
        /// </summary>
        public static string ChangeTerminalTheme {
            get {
                return ResourceManager.GetString("ChangeTerminalTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing statuses....
        /// </summary>
        public static string ChangingStatuses {
            get {
                return ResourceManager.GetString("ChangingStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose 4x6&quot; Printer.
        /// </summary>
        public static string Choose4x6Printer {
            get {
                return ResourceManager.GetString("Choose4x6Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose label.
        /// </summary>
        public static string ChooseLabel {
            get {
                return ResourceManager.GetString("ChooseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the month your financial year starts.
        /// </summary>
        public static string ChooseStartMonth {
            get {
                return ResourceManager.GetString("ChooseStartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string CityLabel {
            get {
                return ResourceManager.GetString("CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Filter Menu.
        /// </summary>
        public static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Window.
        /// </summary>
        public static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN22 forms.
        /// </summary>
        public static string CN22Forms {
            get {
                return ResourceManager.GetString("CN22Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN22 Label Printer.
        /// </summary>
        public static string CN22LabelPrinter {
            get {
                return ResourceManager.GetString("CN22LabelPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN22 Settings.
        /// </summary>
        public static string CN22Settings {
            get {
                return ResourceManager.GetString("CN22Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour Browser.
        /// </summary>
        public static string ColourBrowser {
            get {
                return ResourceManager.GetString("ColourBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Sample.
        /// </summary>
        public static string CommercialSample {
            get {
                return ResourceManager.GetString("CommercialSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string CompanyLabel {
            get {
                return ResourceManager.GetString("CompanyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare sales in selected countries (select country or group of countries).
        /// </summary>
        public static string CompareSalesCountries {
            get {
                return ResourceManager.GetString("CompareSalesCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare sales on selected marketplaces (select marketplace or group of marketplaces).
        /// </summary>
        public static string CompareSalesPlatforms {
            get {
                return ResourceManager.GetString("CompareSalesPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the operation?.
        /// </summary>
        public static string ConfirmCancelOperation {
            get {
                return ResourceManager.GetString("ConfirmCancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm printer.
        /// </summary>
        public static string ConfirmPrinter {
            get {
                return ResourceManager.GetString("ConfirmPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you want to print {0} labels.
        /// </summary>
        public static string ConfirmPrintLabels {
            get {
                return ResourceManager.GetString("ConfirmPrintLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Value.
        /// </summary>
        public static string ConfirmValue {
            get {
                return ResourceManager.GetString("ConfirmValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your choice.
        /// </summary>
        public static string ConfirmYourChoice {
            get {
                return ResourceManager.GetString("ConfirmYourChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country {0} is already added to the list.
        /// </summary>
        public static string CountryAlreadyAdded {
            get {
                return ResourceManager.GetString("CountryAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Orders.
        /// </summary>
        public static string CurrentOrders {
            get {
                return ResourceManager.GetString("CurrentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Date Range.
        /// </summary>
        public static string CustomDateRange {
            get {
                return ResourceManager.GetString("CustomDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error while accessing the database. Would you like to try again?.
        /// </summary>
        public static string DatabaseAccessError {
            get {
                return ResourceManager.GetString("DatabaseAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully retrieved. Now you can display it as a chart, or save it as a CSV file.
        /// </summary>
        public static string DataRetrievedSuccess {
            get {
                return ResourceManager.GetString("DataRetrievedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date must be earlier than the end date. Currently, the start date is {0}, and the end date is {1}. Please correct the date range to generate the sales report for the specified period..
        /// </summary>
        public static string DateRangeError {
            get {
                return ResourceManager.GetString("DateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete label.
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliveries.
        /// </summary>
        public static string Deliveries {
            get {
                return ResourceManager.GetString("Deliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 4x6&quot; Label Printer.
        /// </summary>
        public static string Disable4x6LabelPrinter {
            get {
                return ResourceManager.GetString("Disable4x6LabelPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display moving average overlaid on exact results.
        /// </summary>
        public static string DisplayMovingAverage {
            get {
                return ResourceManager.GetString("DisplayMovingAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  done..
        /// </summary>
        public static string DoneMessage {
            get {
                return ResourceManager.GetString("DoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading photos.
        /// </summary>
        public static string DownloadingPhotos {
            get {
                return ResourceManager.GetString("DownloadingPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eBay returned confirmation response.
        /// </summary>
        public static string EbayConfirmationResponse {
            get {
                return ResourceManager.GetString("EbayConfirmationResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable 4x6&quot; Label Printer.
        /// </summary>
        public static string Enable4x6LabelPrinter {
            get {
                return ResourceManager.GetString("Enable4x6LabelPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name to search for products.
        /// </summary>
        public static string EnterNameToSearch {
            get {
                return ResourceManager.GetString("EnterNameToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire Recorded Period.
        /// </summary>
        public static string EntireRecordedPeriod {
            get {
                return ResourceManager.GetString("EntireRecordedPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value is not a valid decimal number..
        /// </summary>
        public static string ERRORDecimalNumberIncorrect {
            get {
                return ResourceManager.GetString("ERRORDecimalNumberIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be greater than zero..
        /// </summary>
        public static string ERRORNumberMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ERRORNumberMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing label template.
        /// </summary>
        public static string ErrorRemovingLabelTemplateMessage {
            get {
                return ResourceManager.GetString("ErrorRemovingLabelTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a numeric value.
        /// </summary>
        public static string ErrorValidatingMessage {
            get {
                return ResourceManager.GetString("ErrorValidatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating.
        /// </summary>
        public static string ErrorValidatingTitle {
            get {
                return ResourceManager.GetString("ErrorValidatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential Values.
        /// </summary>
        public static string EssentialValues {
            get {
                return ResourceManager.GetString("EssentialValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU.
        /// </summary>
        public static string EU {
            get {
                return ResourceManager.GetString("EU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EU+Iceland+Norway+Switzerland+Liechtenstein.
        /// </summary>
        public static string EUPlus {
            get {
                return ResourceManager.GetString("EUPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to leave feedback for item {0} out of {1}, item id: {2}, transaction id: {3} from buyer {4}.
        /// </summary>
        public static string FeedbackLeftFailed {
            get {
                return ResourceManager.GetString("FeedbackLeftFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for item ({0}) {1} out of {2} left successfully.
        /// </summary>
        public static string FeedbackLeftSuccess {
            get {
                return ResourceManager.GetString("FeedbackLeftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetched all data needed to leave feedback for all orders, attempting to do that now.
        /// </summary>
        public static string FetchedDataForFeedback {
            get {
                return ResourceManager.GetString("FetchedDataForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching {0} orders from the database.
        /// </summary>
        public static string FetchingOnlyOrders {
            get {
                return ResourceManager.GetString("FetchingOnlyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Orders....
        /// </summary>
        public static string FetchingOrders {
            get {
                return ResourceManager.GetString("FetchingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Orders.
        /// </summary>
        public static string FetchOrders {
            get {
                return ResourceManager.GetString("FetchOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch Orders.
        /// </summary>
        public static string FetchOrdersButtonText {
            get {
                return ResourceManager.GetString("FetchOrdersButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all fields, correctly.
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Line:.
        /// </summary>
        public static string FirstLineLabel {
            get {
                return ResourceManager.GetString("FirstLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        public static string Flip {
            get {
                return ResourceManager.GetString("Flip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip new orders.
        /// </summary>
        public static string FlipNewOrders {
            get {
                return ResourceManager.GetString("FlipNewOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward 7 Days.
        /// </summary>
        public static string Forward7Days {
            get {
                return ResourceManager.GetString("Forward7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Charts.
        /// </summary>
        public static string GenerateCharts {
            get {
                return ResourceManager.GetString("GenerateCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate CSV File.
        /// </summary>
        public static string GenerateCSVFile {
            get {
                return ResourceManager.GetString("GenerateCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Data.
        /// </summary>
        public static string GenerateData {
            get {
                return ResourceManager.GetString("GenerateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate data for Click and Drop.
        /// </summary>
        public static string GenerateDataForClickAndDrop {
            get {
                return ResourceManager.GetString("GenerateDataForClickAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting the details of all orders....
        /// </summary>
        public static string GettingOrderDetails {
            get {
                return ResourceManager.GetString("GettingOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift.
        /// </summary>
        public static string Gift {
            get {
                return ResourceManager.GetString("Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height in the landscape orientation must not be greater than 100..
        /// </summary>
        public static string HeightInLandscapeOrientation {
            get {
                return ResourceManager.GetString("HeightInLandscapeOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height in mm.
        /// </summary>
        public static string HeightInMm {
            get {
                return ResourceManager.GetString("HeightInMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be greater than 0..
        /// </summary>
        public static string HeightMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("HeightMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must not be greater than 160..
        /// </summary>
        public static string HeightMustNotBeGreaterThan {
            get {
                return ResourceManager.GetString("HeightMustNotBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed - text in the clipboard has incorrect format.
        /// </summary>
        public static string IncorrectFormatMessage {
            get {
                return ResourceManager.GetString("IncorrectFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect SKU.
        /// </summary>
        public static string IncorrectSKU {
            get {
                return ResourceManager.GetString("IncorrectSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Products.
        /// </summary>
        public static string InitialText {
            get {
                return ResourceManager.GetString("InitialText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock from all suppliers.
        /// </summary>
        public static string InStockFromAllSuppliers {
            get {
                return ResourceManager.GetString("InStockFromAllSuppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid text in the clipboard.
        /// </summary>
        public static string InvalidClipboardFormatTitle {
            get {
                return ResourceManager.GetString("InvalidClipboardFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is not a valid image format..
        /// </summary>
        public static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU you have entered is invalid.
        /// </summary>
        public static string InvalidSKUE_ntered {
            get {
                return ResourceManager.GetString("InvalidSKUE ntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU you have entered is invalid.
        /// </summary>
        public static string InvalidSKUEntered {
            get {
                return ResourceManager.GetString("InvalidSKUEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is VAT Registered.
        /// </summary>
        public static string IsVATRegisteredLabel {
            get {
                return ResourceManager.GetString("IsVATRegisteredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ItemsLabel {
            get {
                return ResourceManager.GetString("ItemsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one invoice is for Jeff Bezos. Do you want to continue with printing?.
        /// </summary>
        public static string JeffBezosConfirmation {
            get {
                return ResourceManager.GetString("JeffBezosConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeff Bezos detected.
        /// </summary>
        public static string JeffBezosDetected {
            get {
                return ResourceManager.GetString("JeffBezosDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to design at least one label in the Label Manager to be able to print them.
        /// </summary>
        public static string LabelManagerDesignRequiredMessage {
            get {
                return ResourceManager.GetString("LabelManagerDesignRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Name cannot be empty..
        /// </summary>
        public static string LabelNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("LabelNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name is already in use, please use different name..
        /// </summary>
        public static string LabelNameInUse {
            get {
                return ResourceManager.GetString("LabelNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label printer.
        /// </summary>
        public static string LabelPrinter {
            get {
                return ResourceManager.GetString("LabelPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you certain that you want to print invoices on the Label Printer?.
        /// </summary>
        public static string LabelPrinterConfirmation {
            get {
                return ResourceManager.GetString("LabelPrinterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels Manager.
        /// </summary>
        public static string LabelsManager {
            get {
                return ResourceManager.GetString("LabelsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label template removed.
        /// </summary>
        public static string LabelTemplateRemovedMessage {
            get {
                return ResourceManager.GetString("LabelTemplateRemovedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape orientation.
        /// </summary>
        public static string LandscapeOrientation {
            get {
                return ResourceManager.GetString("LandscapeOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Large Font&apos; must be greater than 0..
        /// </summary>
        public static string LargeFontMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("LargeFontMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Financial Year.
        /// </summary>
        public static string LastFinancialYear {
            get {
                return ResourceManager.GetString("LastFinancialYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quarter.
        /// </summary>
        public static string LastQuarter {
            get {
                return ResourceManager.GetString("LastQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaving feedback for {0} order(s).
        /// </summary>
        public static string LeavingFeedbackForOrders {
            get {
                return ResourceManager.GetString("LeavingFeedbackForOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend {
            get {
                return ResourceManager.GetString("Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Lesser Font&apos; must be greater than 0..
        /// </summary>
        public static string LesserFontMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("LesserFontMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Chart.
        /// </summary>
        public static string LineChart {
            get {
                return ResourceManager.GetString("LineChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File with Signature.
        /// </summary>
        public static string LoadFileWithSignature {
            get {
                return ResourceManager.GetString("LoadFileWithSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load picture.
        /// </summary>
        public static string LoadPicture {
            get {
                return ResourceManager.GetString("LoadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load picture of package.
        /// </summary>
        public static string LoadPictureOfPackage {
            get {
                return ResourceManager.GetString("LoadPictureOfPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load picture with logo.
        /// </summary>
        public static string LoadPictureWithLogo {
            get {
                return ResourceManager.GetString("LoadPictureWithLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location&apos;s font.
        /// </summary>
        public static string LocationsFont {
            get {
                return ResourceManager.GetString("LocationsFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main currency.
        /// </summary>
        public static string MainCurrency {
            get {
                return ResourceManager.GetString("MainCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string MarketLabel {
            get {
                return ResourceManager.GetString("MarketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string Marketplace {
            get {
                return ResourceManager.GetString("Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association with marketplace not in use.
        /// </summary>
        public static string MarketplaceAssociationNotInUse {
            get {
                return ResourceManager.GetString("MarketplaceAssociationNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup equals{0}with these prices:.
        /// </summary>
        public static string MarkupEqualsWithThesePrices {
            get {
                return ResourceManager.GetString("MarkupEqualsWithThesePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May Also Fit.
        /// </summary>
        public static string MayAlsoFit {
            get {
                return ResourceManager.GetString("MayAlsoFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multidrawer&apos;s font.
        /// </summary>
        public static string MultidrawersFont {
            get {
                return ResourceManager.GetString("MultidrawersFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the only one product.
        /// </summary>
        public static string NameOfTheOnlyOneProduct {
            get {
                return ResourceManager.GetString("NameOfTheOnlyOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the sender.
        /// </summary>
        public static string NameOfTheSender {
            get {
                return ResourceManager.GetString("NameOfTheSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed - no connection to the database.
        /// </summary>
        public static string NoDatabaseConnectionMessage {
            get {
                return ResourceManager.GetString("NoDatabaseConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Connection Error.
        /// </summary>
        public static string NoDatabaseConnectionTitle {
            get {
                return ResourceManager.GetString("NoDatabaseConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No labels designed.
        /// </summary>
        public static string NoLabelsDesignedMessage {
            get {
                return ResourceManager.GetString("NoLabelsDesignedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new orders to download.
        /// </summary>
        public static string NoNewOrders {
            get {
                return ResourceManager.GetString("NoNewOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No orders downloaded yet.
        /// </summary>
        public static string NoOrdersDownloadedMessage {
            get {
                return ResourceManager.GetString("NoOrdersDownloadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to download orders first.
        /// </summary>
        public static string NoOrdersDownloadedTitle {
            get {
                return ResourceManager.GetString("NoOrdersDownloadedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No printers installed.
        /// </summary>
        public static string NoPrintersInstalled {
            get {
                return ResourceManager.GetString("NoPrintersInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no printers installed in the system.
        /// </summary>
        public static string NoPrintersInstalledMessage {
            get {
                return ResourceManager.GetString("NoPrintersInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed - there is no text in the clipboard.
        /// </summary>
        public static string NoTextInClipboardMessage {
            get {
                return ResourceManager.GetString("NoTextInClipboardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not found in the clipboard.
        /// </summary>
        public static string NoTextInClipboardTitle {
            get {
                return ResourceManager.GetString("NoTextInClipboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with this MPN {0} already exists..
        /// </summary>
        public static string ObjectMPNExists {
            get {
                return ResourceManager.GetString("ObjectMPNExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with this name {0} already exists..
        /// </summary>
        public static string ObjectNameExists {
            get {
                return ResourceManager.GetString("ObjectNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with this short name {0} already exists..
        /// </summary>
        public static string ObjectShortNameExists {
            get {
                return ResourceManager.GetString("ObjectShortNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was completed before the cancelation was executed.
        /// </summary>
        public static string OperationCompletedBeforeCancel {
            get {
                return ResourceManager.GetString("OperationCompletedBeforeCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Currency.
        /// </summary>
        public static string OrderCurrency {
            get {
                return ResourceManager.GetString("OrderCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid on.
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details:.
        /// </summary>
        public static string OrderDetailsLabel {
            get {
                return ResourceManager.GetString("OrderDetailsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderIDLabel {
            get {
                return ResourceManager.GetString("OrderIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed - order has not been downloaded yet.
        /// </summary>
        public static string OrderNotDownloadedMessage {
            get {
                return ResourceManager.GetString("OrderNotDownloadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not processed yet.
        /// </summary>
        public static string OrderNotProcessedTitle {
            get {
                return ResourceManager.GetString("OrderNotProcessedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Browser.
        /// </summary>
        public static string OrdersBrowser {
            get {
                return ResourceManager.GetString("OrdersBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} order selected.
        /// </summary>
        public static string OrderSelected {
            get {
                return ResourceManager.GetString("OrderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success - {0} order(s) processed.
        /// </summary>
        public static string OrdersProcessedMessage {
            get {
                return ResourceManager.GetString("OrdersProcessedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} orders selected.
        /// </summary>
        public static string OrdersSelected {
            get {
                return ResourceManager.GetString("OrdersSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid on.
        /// </summary>
        public static string PaidOnLabel {
            get {
                return ResourceManager.GetString("PaidOnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters/Types.
        /// </summary>
        public static string ParametersTypes {
            get {
                return ResourceManager.GetString("ParametersTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one order is not processed yet, give it a moment.
        /// </summary>
        public static string PartialOrderNotProcessedMessage {
            get {
                return ResourceManager.GetString("PartialOrderNotProcessedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not processed yet.
        /// </summary>
        public static string PartialOrderNotProcessedTitle {
            get {
                return ResourceManager.GetString("PartialOrderNotProcessedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo #{0} of {1}.
        /// </summary>
        public static string PhotoDescription {
            get {
                return ResourceManager.GetString("PhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo of the Package.
        /// </summary>
        public static string PhotoOfThePackage {
            get {
                return ResourceManager.GetString("PhotoOfThePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo with Logo.
        /// </summary>
        public static string PhotoWithLogo {
            get {
                return ResourceManager.GetString("PhotoWithLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie Chart.
        /// </summary>
        public static string PieChart {
            get {
                return ResourceManager.GetString("PieChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode:.
        /// </summary>
        public static string PostcodeLabel {
            get {
                return ResourceManager.GetString("PostcodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing data for C&apos;n&apos;D for .
        /// </summary>
        public static string PreparingDataForCnDMessagePart1 {
            get {
                return ResourceManager.GetString("PreparingDataForCnDMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  order(s)....
        /// </summary>
        public static string PreparingDataForCnDMessagePart2 {
            get {
                return ResourceManager.GetString("PreparingDataForCnDMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price for the only one product.
        /// </summary>
        public static string PriceForTheOnlyOneProduct {
            get {
                return ResourceManager.GetString("PriceForTheOnlyOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-VAT price paid.
        /// </summary>
        public static string PricePaidExVat {
            get {
                return ResourceManager.GetString("PricePaidExVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex-VAT price paid ({0}).
        /// </summary>
        public static string PricePaidWithCurrencyExVat {
            get {
                return ResourceManager.GetString("PricePaidWithCurrencyExVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price ({0}) including VAT .
        /// </summary>
        public static string PricePaidWithCurrencyIncVat {
            get {
                return ResourceManager.GetString("PricePaidWithCurrencyIncVat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print CN22 Label.
        /// </summary>
        public static string PrintCN22Label {
            get {
                return ResourceManager.GetString("PrintCN22Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print CN22s.
        /// </summary>
        public static string PrintCN22s {
            get {
                return ResourceManager.GetString("PrintCN22s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print {0} copies.
        /// </summary>
        public static string PrintCopies {
            get {
                return ResourceManager.GetString("PrintCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print example.
        /// </summary>
        public static string PrintExample {
            get {
                return ResourceManager.GetString("PrintExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string Printing {
            get {
                return ResourceManager.GetString("Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing {0} invoices.
        /// </summary>
        public static string PrintingInvoicesCount {
            get {
                return ResourceManager.GetString("PrintingInvoicesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing on {0}, is that correct?.
        /// </summary>
        public static string PrintingOn {
            get {
                return ResourceManager.GetString("PrintingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing summary of {0} orders....
        /// </summary>
        public static string PrintingSummaryOfOrders {
            get {
                return ResourceManager.GetString("PrintingSummaryOfOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print invoices.
        /// </summary>
        public static string PrintInvoices {
            get {
                return ResourceManager.GetString("PrintInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Invoices.
        /// </summary>
        public static string PrintInvoicesButtonText {
            get {
                return ResourceManager.GetString("PrintInvoicesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print label.
        /// </summary>
        public static string PrintLabel {
            get {
                return ResourceManager.GetString("PrintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print line for one product.
        /// </summary>
        public static string PrintLineForOneProduct {
            get {
                return ResourceManager.GetString("PrintLineForOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print lines for all sold products.
        /// </summary>
        public static string PrintLinesForAllSoldProducts {
            get {
                return ResourceManager.GetString("PrintLinesForAllSoldProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print summary.
        /// </summary>
        public static string PrintSummary {
            get {
                return ResourceManager.GetString("PrintSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to process data of Amazon orders from the clipboard....
        /// </summary>
        public static string ProcessingAmazonOrdersMessage {
            get {
                return ResourceManager.GetString("ProcessingAmazonOrdersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} added.
        /// </summary>
        public static string ProductAddedMessage {
            get {
                return ResourceManager.GetString("ProductAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product added.
        /// </summary>
        public static string ProductAddedTitle {
            get {
                return ResourceManager.GetString("ProductAddedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This product is already assigned to box {0} to location [{1},{2}].
        /// </summary>
        public static string ProductAlreadyAssigned {
            get {
                return ResourceManager.GetString("ProductAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with this MPN already exists: {0}.
        /// </summary>
        public static string ProductMpnExists {
            get {
                return ResourceManager.GetString("ProductMpnExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product with this name already exists: {0}.
        /// </summary>
        public static string ProductNameExists {
            get {
                return ResourceManager.GetString("ProductNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name&apos;s font.
        /// </summary>
        public static string ProductNameFont {
            get {
                return ResourceManager.GetString("ProductNameFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object with this short name already exists: {0}.
        /// </summary>
        public static string ProductShortNameExists {
            get {
                return ResourceManager.GetString("ProductShortNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products&apos;s mpn&apos;s font.
        /// </summary>
        public static string ProductsMpnFont {
            get {
                return ResourceManager.GetString("ProductsMpnFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products shown.
        /// </summary>
        public static string ProductsShown {
            get {
                return ResourceManager.GetString("ProductsShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity on eBay is the same as new quantity - revision skipped.
        /// </summary>
        public static string QuantitySameRevisionSkipped {
            get {
                return ResourceManager.GetString("QuantitySameRevisionSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing product details.
        /// </summary>
        public static string RefreshingProductDetails {
            get {
                return ResourceManager.GetString("RefreshingProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh orders every 5 mins.
        /// </summary>
        public static string RefreshOrdersEvery5Mins {
            get {
                return ResourceManager.GetString("RefreshOrdersEvery5Mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Photos.
        /// </summary>
        public static string RegularPhotos {
            get {
                return ResourceManager.GetString("RegularPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from QuickBooks.
        /// </summary>
        public static string RemoveFromQuickBooks {
            get {
                return ResourceManager.GetString("RemoveFromQuickBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove {0}.
        /// </summary>
        public static string RemoveLabelConfirmationMessage {
            get {
                return ResourceManager.GetString("RemoveLabelConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove supplier.
        /// </summary>
        public static string RemoveSupplier {
            get {
                return ResourceManager.GetString("RemoveSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names &quot;Return Label&quot; and &quot;Address Label&quot; are reserved for return and address labels.
        /// </summary>
        public static string ReservedNamesInformation {
            get {
                return ResourceManager.GetString("ReservedNamesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned goods.
        /// </summary>
        public static string ReturnedGoods {
            get {
                return ResourceManager.GetString("ReturnedGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale of Goods.
        /// </summary>
        public static string SaleOfGoods {
            get {
                return ResourceManager.GetString("SaleOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Summary.
        /// </summary>
        public static string SalesSummary {
            get {
                return ResourceManager.GetString("SalesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale statistics:.
        /// </summary>
        public static string SaleStatistics {
            get {
                return ResourceManager.GetString("SaleStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image file.
        /// </summary>
        public static string SaveImageFile {
            get {
                return ResourceManager.GetString("SaveImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save product details.
        /// </summary>
        public static string SaveProductDetails {
            get {
                return ResourceManager.GetString("SaveProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Line:.
        /// </summary>
        public static string SecondLineLabel {
            get {
                return ResourceManager.GetString("SecondLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name:.
        /// </summary>
        public static string SecondNameLabel {
            get {
                return ResourceManager.GetString("SecondNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all new.
        /// </summary>
        public static string SelectAllNew {
            get {
                return ResourceManager.GetString("SelectAllNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Amazon orders.
        /// </summary>
        public static string SelectAmazonOrders {
            get {
                return ResourceManager.GetString("SelectAmazonOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one country or group of countries from the list.
        /// </summary>
        public static string SelectCountryOrGroup {
            get {
                return ResourceManager.GetString("SelectCountryOrGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select eBay orders.
        /// </summary>
        public static string SelectEbayOrders {
            get {
                return ResourceManager.GetString("SelectEbayOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file with signature.
        /// </summary>
        public static string SelectFileWithSignature {
            get {
                return ResourceManager.GetString("SelectFileWithSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select status.
        /// </summary>
        public static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select the month in which your tax year starts.
        /// </summary>
        public static string SelectTaxYearStartMonth {
            get {
                return ResourceManager.GetString("SelectTaxYearStartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Name.
        /// </summary>
        public static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show net prices (indicated when sales consist of net and gross prices).
        /// </summary>
        public static string ShowNetPrices {
            get {
                return ResourceManager.GetString("ShowNetPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sold on markets.
        /// </summary>
        public static string SoldOnMarkets {
            get {
                return ResourceManager.GetString("SoldOnMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between two central lines.
        /// </summary>
        public static string SpaceBetweenTwoCentralLines {
            get {
                return ResourceManager.GetString("SpaceBetweenTwoCentralLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing quantites with marketplaces.
        /// </summary>
        public static string SyncQuantityWithSalesPlatforms {
            get {
                return ResourceManager.GetString("SyncQuantityWithSalesPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Top Font&apos; must be greater than 0..
        /// </summary>
        public static string TopFontMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopFontMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Margin.
        /// </summary>
        public static string TopMargin {
            get {
                return ResourceManager.GetString("TopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Top Margin&apos; must not be negative..
        /// </summary>
        public static string TopMarginMustNotBeNegative {
            get {
                return ResourceManager.GetString("TopMarginMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        public static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Orders.
        /// </summary>
        public static string TotalOrderCount {
            get {
                return ResourceManager.GetString("TotalOrderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracked.
        /// </summary>
        public static string Tracked {
            get {
                return ResourceManager.GetString("Tracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn tracking on/off.
        /// </summary>
        public static string TurnTrackOnOff {
            get {
                return ResourceManager.GetString("TurnTrackOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of content.
        /// </summary>
        public static string TypeOfContent {
            get {
                return ResourceManager.GetString("TypeOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of label.
        /// </summary>
        public static string TypeOfLabel {
            get {
                return ResourceManager.GetString("TypeOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UK.
        /// </summary>
        public static string UK {
            get {
                return ResourceManager.GetString("UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown marketplace.
        /// </summary>
        public static string UnknownMarketplace {
            get {
                return ResourceManager.GetString("UnknownMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown selling platform.
        /// </summary>
        public static string UnknownSellingPlatform {
            get {
                return ResourceManager.GetString("UnknownSellingPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Quantities on Marketplaces.
        /// </summary>
        public static string UpdateQuantitiesOnMarketplaces {
            get {
                return ResourceManager.GetString("UpdateQuantitiesOnMarketplaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating data.
        /// </summary>
        public static string UpdatingData {
            get {
                return ResourceManager.GetString("UpdatingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating numbers on markets.
        /// </summary>
        public static string UpdatingNumbersOnMarkets {
            get {
                return ResourceManager.GetString("UpdatingNumbersOnMarkets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading logo photo.
        /// </summary>
        public static string UploadingLogoPhoto {
            get {
                return ResourceManager.GetString("UploadingLogoPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading photo.
        /// </summary>
        public static string UploadingPhoto {
            get {
                return ResourceManager.GetString("UploadingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo of Package.
        /// </summary>
        public static string UploadPhotoOfPackage {
            get {
                return ResourceManager.GetString("UploadPhotoOfPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo with Logo.
        /// </summary>
        public static string UploadPhotoWithLogo {
            get {
                return ResourceManager.GetString("UploadPhotoWithLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Explorer.
        /// </summary>
        public static string WatchExplorer {
            get {
                return ResourceManager.GetString("WatchExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight for the only one product.
        /// </summary>
        public static string WeightForTheOnlyOneProduct {
            get {
                return ResourceManager.GetString("WeightForTheOnlyOneProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which countries to include.
        /// </summary>
        public static string WhichCountriesToInclude {
            get {
                return ResourceManager.GetString("WhichCountriesToInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which markets to include.
        /// </summary>
        public static string WhichMarketsToInclude {
            get {
                return ResourceManager.GetString("WhichMarketsToInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must not be greater than 100 in the landscape mode..
        /// </summary>
        public static string WidthInLandscapeMode {
            get {
                return ResourceManager.GetString("WidthInLandscapeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width in mm.
        /// </summary>
        public static string WidthInMm {
            get {
                return ResourceManager.GetString("WidthInMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must be greater than 0..
        /// </summary>
        public static string WidthMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("WidthMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must not be greater than 160..
        /// </summary>
        public static string WidthMustNotBeGreaterThan160 {
            get {
                return ResourceManager.GetString("WidthMustNotBeGreaterThan160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
